[package]
name = "ezra/tutorialgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
dataservicetyped = "leifstout/dataservicetyped@1.0.3"

[server-dependencies]
profilestore = "2jammers/profilestore@0.1.0"